# Copyright (c) 2018-2021, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: cuml-l4t
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - VERSION_SUFFIX

requirements:
  build:
    - python x.x
    - setuptools
    - cython>=0.29,<0.30
    - cmake>=3.20.1
    - treelite=2.0.0
    - cudf-l4t {{ minor_version }}
    - libcuml-l4t={{ version }}
    - ucx-py-l4t
    - ucx-proc-l4t=*=gpu
  run:
    - python x.x
    - cudf-l4t {{ minor_version }}
    - dask-cudf-l4t {{ minor_version }}
    - libcuml-l4t={{ version }}
    - cupy-l4t>=7.8.0
    - treelite=2.0.0
    - nccl-l4t>=2.9.9
    - ucx-py-l4t
    - ucx-proc-l4t=*=gpu
    - dask>=2021.6.0
    - distributed>=2021.6.0
    - joblib >=0.11

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuML library
